# Generated by Django 4.2.5 on 2023-10-29 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=16, unique=True)),
                ('plan_id', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('code_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('included_services', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='registeredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
