# Generated by Django 4.2.5 on 2023-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0002_appuser_subscription_end_appuser_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('included_services', models.TextField()),
            ],
        ),
    ]
