# Generated by Django 4.2.5 on 2023-09-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0003_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
