# Generated by Django 4.2.5 on 2023-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0005_subscriptioncodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_ID', models.CharField(max_length=16, unique=True)),
                ('subscription_plan', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
