# Generated by Django 4.2.5 on 2023-10-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0006_receivedpayments_alter_appuser_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedpayments',
            old_name='subscription_ID',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='receivedpayments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receivedpayments',
            name='subscription_plan',
        ),
    ]
