# Generated by Django 4.2.5 on 2023-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0007_rename_subscription_id_receivedpayments_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedpayments',
            name='plan_id',
            field=models.CharField(default='some_default_value', max_length=255),
            preserve_default=False,
        ),
    ]
