# Generated by Django 4.2.5 on 2023-10-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0009_subscriptionplan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='registeredDate',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
