# Generated by Django 4.2.5 on 2023-10-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0002_receivedpayments_subscriptioncodes_subscriptionplan_and_more'),
        ('reservehub_app', '0011_alter_appuser_registereddate'),
    ]

    operations = [
    ]
