# Generated by Django 4.2.5 on 2023-11-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0012_merge_20231030_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='newsletter_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='requests_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='reservation_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
