# Generated by Django 4.2.5 on 2023-11-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0014_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
