# Generated by Django 4.2.5 on 2023-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0015_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(default='asdasdads', max_length=255),
            preserve_default=False,
        ),
    ]
