# Generated by Django 4.2.5 on 2023-11-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0017_businesstype_alter_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='type_id',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='business_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
