# Generated by Django 4.2.5 on 2023-11-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservehub_app', '0018_businesstype_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='type_id',
        ),
    ]
